[package]
name = "minesweeper"
version = "0.2.0"
authors = ["thomas9911 <thomastimmer11@hotmail.com>"]
build = "build.rs"


[dependencies]
structopt = "0.2"
piston_window = "0.85.0"
rand = "*"
rusttype="*"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[package.metadata.winres]